name: Runner Test

on:
  push:
    branches: [deployment]
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: [self-hosted, hopin-prod]
    steps:
      - name: Hello
        run: |
          echo "runner is alive: $(hostname) at $(date)"
